---
fleet_ip: 172.17.8.103
fleet_port: 49153
# Container names should be only [a-zA-Z-]+, for readibility and due to
# joining their name with env and pod name in _normalize_container_names@config.py
# FIXME - add validation for that
pods:
  giant-weather:
    #all_or_none: true
    #all_together: "{{ all_together }}"
    all_or_none: false
    all_together: false
    containers:
        redis:
          image: docker.io/redis
        front:
          image: docker.io/vespian/currentweather-go
          external_ports:
              - 8080:8080
          # FIXME links can only be in form of container:name, due to name
          # normalization
          links:
              - redis:redis
  just-redis:
    all_or_none: true
    all_together: true
    containers:
        redis:
          image: docker.io/redis

# Variable names should never include dashes, they will be interpreted as
# a subtraction in the template!
# FIXME - add validation for that
environments:
  dev:
    all_together: false
    weather_port: 8082
  test:
    all_together: true
    weather_port: 8081
  prod:
    all_together: true
    weather_port: 8080
